# .goreleaser.yaml
project_name: serein

builds:
  - id: serein
    main: ./
    binary: serein
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
    goarch:
      - amd64

checksum:
  name_template: 'checksums.txt'

release:
  github:
    owner: nixuris
    name: serein-cli
