name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - run: |
          gofmt -w .
          git diff --exit-code
      - uses: cachix/install-nix-action@v27
      - run: nix build .#default
      - run: nix flake check
